---
title: "Math Final"
author: "Matthew Vanaman"
date: '`r format(Sys.Date(), "%m-%d-%Y")`'
monofont: Courier New
output:
  pdf_document: 
    latex_engine: xelatex
  word_document: default
header-includes: \usepackage{tikz,xcolor,listings}
---
`r knitr::opts_knit$set(root.dir='..')`

```{r, include=FALSE, cache=TRUE}
library(ProjectTemplate); load.project()
```

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, comment = NA)
options(scipen = 999)
knitr::opts_chunk$set(engine.path = "/anaconda3/bin/python")
```


# 7.11

## (a)

$$\frac {\partial} {\partial \beta_1} = \alpha + \beta_1 x_{i1} + \beta_2 x_{i2} + \beta_3 x_{i2}^2 + \beta_4 x_{i2}^3 + \beta_5 x_{i3} + \beta_6 x_{i4} + \beta_7 x_{i3} x_{i4},$$
Derivative of a constant is zero, so drop $\alpha$:
$$= \beta_1 x_{i1} + \beta_2 x_{i2} + \beta_3 x_{i2}^2 + \beta_4 x_{i2}^3 + \beta_5 x_{i3} + \beta_6 x_{i4} + \beta_7 x_{i3} x_{i4},$$
Break up across addition and subtration, then again across multiplication:
$$= \frac {\partial} {\partial \beta_1}\beta_1  x_{i1} + \frac {\partial} {\partial \beta_1}\beta_2 \frac {\partial} {\partial \beta_1} x_{i2} + \frac {\partial} {\partial \beta_1}\beta_3 \frac {\partial} {\partial \beta_1}x_{i2}^2 + \frac {\partial} {\partial \beta_1}\beta_4 \frac {\partial} {\partial \beta_1}x_{i2}^3 + \frac {\partial} {\partial \beta_1}\beta_5 \frac {\partial} {\partial \beta_1}x_{i3} + \frac {\partial} {\partial \beta_1}\beta_6 \frac {\partial} {\partial \beta_1}x_{i4} + \frac {\partial} {\partial \beta_1}\beta_7 \frac {\partial} {\partial \beta_1}x_{i3} \frac {\partial} {\partial \beta_1}x_{i4},$$
All other independent variables are treated as constants:
$$= \frac {\partial} {\partial \beta_1}\beta_1 x_{i1} + 0 (0) + 0(0) + 0(0) + 0(0) + 0(0) + 0(0)(0),$$
Bring the constant out:
$$= \beta_1 \frac {\partial} {\partial \beta_1} x_{i1} = \beta_1(1) = \beta_1.$$











# 9.10


# 10.9