---
title: "Math HW7"
author: "Matthew Vanaman"
date: '`r format(Sys.Date(), "%m-%d-%Y")`'
monofont: Courier New
output:
  pdf_document: 
    latex_engine: xelatex
  word_document: default
header-includes: \usepackage{tikz,xcolor,listings}
---
`r knitr::opts_knit$set(root.dir='..')`

```{r, include=FALSE, cache=TRUE}
library(ProjectTemplate); load.project()
```

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, comment = NA)
options(scipen = 999)
knitr::opts_chunk$set(engine.path = "/anaconda3/bin/python")
np <- reticulate::import("numpy")
sympy <- reticulate::import_from_path("sympy", path = "/anaconda3/lib/python3.7/site-packages")
```

 7.6 (sketch its level sets as well), 7.7, 7.10

## 7.1a

**Answer:** $f(a,b,c,d,e,f) = a \times b \times c \times d \times e \times f$

## 7.3a

**Answer:** 5 \newline

**Work:** \newline


Plug in 3 and 1:
```{r}
(3^2 - 3 * 1 + (6 * 1)^2) / (3 - 3 * 1)
```
So that doesn't work. Need to find some way to cancel out the denominator.

$$x^2 - xy + 6y^2,$$
Set y equal to 1:
$$= x^2 - (x \cdot 1) + (6 \cdot 1)^2,$$
$$= x^2 - x + 6,$$
$$= (x - 3)(x + 2).$$
Plug y back in:
$$= (x - 3y)(x + 2y).$$
Check work:
```{python}
from __future__ import division
from sympy import *
x, y = symbols('x y')
print(expand((x - 3*y) * (x + 2*y)))
```
plug back into original expression:
$$\dfrac{(x - 3y)(x + 2y)}{x - 3y},$$
$$= x + 2y.$$
Plugging in x and y values:
```{r}
3 + 2 * 1
```

## 7.6 (sketch its level sets as well)

### (a)
